# This can be used as a template for an SVG symbol's metadata.
# Just be sure you rename it to have the same name as the SVG, only
# with a a ".toml" extension instead of an ".svg" extension.
#
# So for example, if you want to define metadata for "antler.svg",
# you can make a copy of this file and call it "antler.toml".
#
# Also note that any lines that begin with a "#" are comments,
# so they will be ignored by the code.
#
# Note also that all properties that are booleans
# (i.e., true or false) will, unless otherwise noted,
# always default to false if left undefined.

# If true, this indicates that the symbol should always have
# a symbol nested within its nesting area(s).
always_nest = false

# If true, this indicates that the symbol should always
# be nested inside another symbol's nesting area.
always_be_nested = false

# If true, this indicates that the symbol should never
# be nested inside another symbol's nesting area.
never_be_nested = false

# If true, this indicates that any symbols nested on this
# symbolâ€™s nesting area should have their colors inverted.
invert_nested = false

# If set to an array of strings, this indicates the kinds of
# attachment points that this symbol can attach to.  If not
# defined, this symbol will be able to attach to any attachment
# point.
attach_to = ["tail", "leg", "arm", "horn", "crown"]

# If true, symbol will rotate clockwise instead of default counter-clockwise
rotate_clockwise = false

# If true, this indicates that we should never horizontally flip the
# orientation of a symbol when attaching it.  Otherwise, we will flip
# the symbol horizontally if it's facing left, and flip it horizontally
# again if it's facing down.
never_flip_attachments = false

# If true, symbol may be used as large background shape in some compositions.
background = false
