# If true, this indicates that the symbol should always have

# a symbol nested within its nesting area(s).

always_nest = true



# If true, this indicates that the symbol nested on this

# symbolâ€™s nesting area should have its colors inverted.

invert_nested = true
